const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Configuration
const REPO_ROOT = path.resolve(__dirname, '..');
const PROGRAM_DIR = path.join(REPO_ROOT, 'programs');
const FRONTEND_DIR = path.join(REPO_ROOT, 'app');

const SOURCE_IDL = path.join(PROGRAM_DIR, 'target/idl/terraledger.json');
const DEST_JSON = path.join(FRONTEND_DIR, 'src/lib/anchor/terraledger.json');
const DEST_TS = path.join(FRONTEND_DIR, 'src/lib/anchor/terraledger.ts');

function sync() {
    console.log('--- IDL Sync ---');

    // 1. Check if source IDL exists, if not build it
    if (!fs.existsSync(SOURCE_IDL)) {
        console.log('Source IDL not found. Running anchor build...');
        try {
            execSync('anchor build', { cwd: PROGRAM_DIR, stdio: 'inherit' });
        } catch (error) {
            console.error('Error: anchor build failed');
            process.exit(1);
        }
    }

    if (!fs.existsSync(SOURCE_IDL)) {
        console.error(`Error: Source IDL still not found at ${SOURCE_IDL}`);
        process.exit(1);
    }

    // 2. Read IDL
    const idlContent = fs.readFileSync(SOURCE_IDL, 'utf8');
    const idl = JSON.parse(idlContent);

    // 3. Copy JSON to frontend
    fs.writeFileSync(DEST_JSON, JSON.stringify(idl, null, 2));
    console.log(`Copied JSON IDL to: ${path.relative(REPO_ROOT, DEST_JSON)}`);

    // 4. Generate TS types
    const tsContent = `/**
 * This file was automatically generated by scripts/sync-idl.js.
 * DO NOT EDIT MANUALLY.
 */

import { Idl, Program } from "@coral-xyz/anchor";

export type Terraledger = ${JSON.stringify(idl, null, 2)};

export const IDL: Terraledger = ${JSON.stringify(idl, null, 2)};

export type TerraledgerProgram = Program<Terraledger>;
`;

    fs.writeFileSync(DEST_TS, tsContent);
    console.log(`Generated TS types to: ${path.relative(REPO_ROOT, DEST_TS)}`);

    // 5. Show confirmation and diff summary
    const timestamp = new Date().toISOString();
    console.log(`Sync completed at: ${timestamp}`);
    
    try {
        console.log('\nDiff summary:');
        const diff = execSync(`git diff --stat ${DEST_JSON} ${DEST_TS}`, { cwd: REPO_ROOT }).toString();
        console.log(diff || 'No changes detected.');
    } catch (error) {
        // git diff might fail if files are not tracked or git is not present
        console.log('Could not generate diff summary.');
    }
}

try {
    sync();
} catch (error) {
    console.error('IDL Sync failed:', error);
    process.exit(1);
}
